---
abstract: 'Create GUI easily with SDL'
author:
  - 'Jerome Quelin <jquelin@gmail.com>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  SDLx::App: 0
  Test::More: 0.88
  strict: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SDLx-GUI
provides:
  SDLx::GUI:
    file: lib/SDLx/GUI.pm
    version: 0.001
  SDLx::GUI::Debug:
    file: lib/SDLx/GUI/Debug.pm
    version: 0.001
  SDLx::GUI::Pack:
    file: lib/SDLx/GUI/Pack.pm
    version: 0.001
  SDLx::GUI::Types:
    file: lib/SDLx/GUI/Types.pm
    version: 0.001
  SDLx::GUI::Widget:
    file: lib/SDLx/GUI/Widget.pm
    version: 0.001
  SDLx::GUI::Widget::Button:
    file: lib/SDLx/GUI/Widget/Button.pm
    version: 0.001
  SDLx::GUI::Widget::Label:
    file: lib/SDLx/GUI/Widget/Label.pm
    version: 0.001
  SDLx::GUI::Widget::Toplevel:
    file: lib/SDLx/GUI/Widget/Toplevel.pm
    version: 0.001
requires:
  Carp: 0
  DateTime: 0
  Exporter::Lite: 0
  List::AllUtils: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Has::Sugar: 0
  MooseX::SemiAffordanceAccessor: 0
  SDL::Color: 0
  SDL::Event: 0
  SDL::Video: 0
  SDLx::Rect: 0
  SDLx::Sprite: 0
  SDLx::Surface: 0
  SDLx::Text: 0
  Time::HiRes: 0
  perl: 5.016
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=SDLx-GUI
  homepage: http://search.cpan.org/dist/SDLx-GUI/
  repository: git://github.com/jquelin/sdlx-gui.git
version: 0.001
x_Dist_Zilla:
  perl:
    version: 5.016002
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@Author::JQUELIN/Git::NextVersion'
      version: 2.006
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::JQUELIN/GatherDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@Author::JQUELIN/Test::Compile'
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::JQUELIN/PodCoverageTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::JQUELIN/PodSyntaxTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::JQUELIN/ReportVersions::Tiny'
      version: 1.08
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::JQUELIN/PruneCruft'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@Author::JQUELIN/PruneFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::JQUELIN/ManifestSkip'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::JQUELIN/AutoPrereqs'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::JQUELIN/ExtraTests'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::JQUELIN/NextRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::JQUELIN/PkgVersion'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@Author::JQUELIN/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@Author::JQUELIN/Prepender'
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::JQUELIN/ExecDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::JQUELIN/ShareDir'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@Author::JQUELIN/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@Author::JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@Author::JQUELIN/Repository'
      version: 0.19
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@Author::JQUELIN/MetaProvides::Package'
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::JQUELIN/MetaConfig'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::HelpWanted
      name: '@Author::JQUELIN/HelpWanted'
      version: 0.2.1
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::JQUELIN/License'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Covenant
      name: '@Author::JQUELIN/Covenant'
      version: 0.1.0
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::JQUELIN/MetaYAML'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::JQUELIN/MetaJSON'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@Author::JQUELIN/ModuleBuild'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Author::JQUELIN/Readme'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::JQUELIN/ReadmeAnyFromPod'
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::JQUELIN/Manifest'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@Author::JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::JQUELIN/TestRelease'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::JQUELIN/Git::Check'
      version: 2.006
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::JQUELIN/Git::Commit'
      version: 2.006
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::JQUELIN/Git::Tag'
      version: 2.006
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@Author::JQUELIN/Git::Push'
      version: 2.006
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::JQUELIN/UploadToCPAN'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300028
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300028
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300028
x_author_pledge:
  version: 1
